version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    container_name: my_db  
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    container_name: my_adminer  
    ports:
      - 8080:8080

  app:
    image: localhost/webservicecourse:latest
    container_name: my_app 
    ports:
      - 8083:8083
    restart: always

